# Generated by Django 4.0.6 on 2022-07-26 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_vendor_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='join_date',
            field=models.DateField(default=datetime.date(2022, 7, 26)),
        ),
    ]
