# Generated by Django 4.0.6 on 2022-07-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='join_date',
        ),
    ]
